version: '3'

tasks:
  deps:
    cmds:
      - go mod tidy

  "generate:easyjson":
    cmds:
      - easyjson -all pkg/nydigits.go

  build:
    deps: [deps, "generate:easyjson", lint, test]
    cmds:
      - go build -v -o bin/nydigits

  lint:
    cmds:
      - golangci-lint run

  test:
    cmds:
      - go test -v ./...

  "test:e2e":
    preconditions:
      - sh: 'curl http://localhost:3000'
    cmds:
      - hurl --test --glob "test/e2e/**/*.hurl"

  "spin:build":
    deps: [deps, "generate:easyjson"]
    cmds:
      - spin build
      - echo "Build done, you can execute spin up now"

  "spin:up":
    cmds:
      - spin up

  "release:local":
    cmds:
      - goreleaser check
      - goreleaser build --single-target
  "release:snapshot":
    cmds:
      - echo "releasing snapshot without tagging release"
      - goreleaser release --snapshot

  "release:github":
    env:
      GITHUB_TOKEN: ""
    vars:
      NEXT_VERSION:
        sh: svu next
    preconditions:
      - sh: '[ -n "$GITHUB_TOKEN" ]'
    cmds:
      - echo "releasing {{.NEXT_VERSION}}"
      - git tag "{{.NEXT_VERSION}}"
      - git push --tags
      - goreleaser --clean
